"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { visualQuestions } from "../questions";
import "../btt.css";

export default function VisualQuiz() {
  const [index, setIndex] = useState(0); const [choice, setChoice] = useState<number | null>(null); const [submitted, setSubmitted] = useState(false); const [answers, setAnswers] = useState<Record<string, boolean>>({}); const [completed, setCompleted] = useState(false);
  const q = visualQuestions[index]; const reveal = submitted; const score = Object.values(answers).filter(Boolean).length;
  useEffect(() => { const saved = JSON.parse(localStorage.getItem("btt-visual-v1") || "{}") as Record<string, boolean>; setAnswers(saved); }, []);
  const submit = () => { if (choice === null) return; const nextAnswers = { ...answers, [q.id]: choice === q.answer }; setAnswers(nextAnswers); setSubmitted(true); localStorage.setItem("btt-visual-v1", JSON.stringify(nextAnswers)); };
  const next = () => { if (index < visualQuestions.length - 1) { setIndex(index + 1); setChoice(null); setSubmitted(false); } else setCompleted(true); };
  const previous = () => { if (index > 0) { setIndex(index - 1); setChoice(null); setSubmitted(false); } };
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (completed || event.metaKey || event.ctrlKey || event.altKey) return; const key = event.key.toLowerCase(); if (!submitted && ["a", "b", "c", "d"].includes(key)) { event.preventDefault(); setChoice("abcd".indexOf(key)); } else if (event.key === "Enter" && (!submitted ? choice !== null : true)) { event.preventDefault(); if (submitted) next(); else submit(); } else if (submitted && event.key === "ArrowRight") { event.preventDefault(); next(); } else if (submitted && event.key === "ArrowLeft") { event.preventDefault(); previous(); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [completed, submitted, choice, index, answers]);
  const restart = () => { setIndex(0); setChoice(null); setSubmitted(false); setAnswers({}); setCompleted(false); localStorage.removeItem("btt-visual-v1"); };
  return <main className="btt-shell"><header className="btt-header"><Link href="/btt" className="home-link">← BTT practice</Link><strong>Visual Signage Quiz</strong><span>{score}/{visualQuestions.length} correct</span></header>{completed ? <section className="quiz-wrap"><article className="quiz-card"><p className="topic-pill">Quiz complete</p><h1>You scored {score} out of {visualQuestions.length}.</h1><p>Keep practising until you can identify each sign and marking at a glance.</p><div className="next-row"><Link href="/btt" className="home-link">Back to practice</Link><button onClick={restart}>Try again →</button></div></article></section> : <section className="quiz-wrap"><div className="quiz-meta"><span>Visual question</span><span>Question {index + 1} of {visualQuestions.length}</span><span>Tap image to zoom</span></div><div className="progress"><span style={{ width: `${(index / visualQuestions.length) * 100}%` }} /></div><article className="quiz-card visual-card"><button className="visual-frame" onClick={() => window.open(q.image, "_blank")} aria-label="Open a larger version of the traffic sign or road visual"><img src={q.image} alt="Traffic sign, road marking or signal to identify" /></button><h1>{q.prompt}</h1><div className="choices">{q.options.map((option, i) => <button disabled={reveal} key={option} className={reveal ? i === q.answer ? "correct" : i === choice ? "incorrect" : "" : choice === i ? "selected" : ""} onClick={() => setChoice(i)}><span>{"ABCD"[i]}</span>{option}</button>)}</div>{!reveal ? <button className="submit" disabled={choice === null} onClick={submit}>Submit answer</button> : <div className="reveal"><b>{answers[q.id] ? "Correct" : "Not quite"}</b><p>{q.explanation}</p><p className="reference">Handbook p.{q.page} · {q.topic}</p><p className="reference">Keyboard: A–D choose · Enter submit/continue · ← → move</p><div className="next-row"><button disabled={index === 0} onClick={previous}>Previous</button><button onClick={next}>{index === visualQuestions.length - 1 ? "Finish quiz →" : "Next question →"}</button></div></div>}</article></section>}</main>;
}
