export type BttQuestion = { id: string; kind: "text" | "visual"; prompt: string; options: string[]; answer: number; explanation: string; page: number; topic: string; image?: string };

const textSeed: Array<[string, string[], number, string, number, string]> = [
  ["What is the minimum age to qualify for a Singapore driving licence?", ["16", "18", "21", "25"], 1, "Applicants must be at least 18 years old.", 3, "Driving licences"],
  ["What must a new Class 3 or 3A driver display during the one-year probation period?", ["L plate", "P plate", "Learner card", "Red flag"], 1, "A probation plate is required at the front and rear.", 5, "New drivers"],
  ["How many demerit points can a probationary motorist accumulate before the new licence is revoked?", ["10 or more", "12 or more", "13 or more", "24 or more"], 2, "A new driver's licence is revoked at 13 or more points during probation.", 5, "DIPS"],
  ["When approaching a roundabout, who must you give way to?", ["Vehicles entering behind you", "Vehicles already in the roundabout", "Vehicles on your left only", "Pedestrians only"], 1, "Give way to traffic already circulating in the roundabout.", 53, "Roundabouts"],
  ["What is the basic keep-left rule?", ["Drive in the right lane unless turning", "Keep left unless overtaking or directed otherwise", "Always use the middle lane", "Keep left only below 50 km/h"], 1, "Keep left unless overtaking or road conditions/directive require otherwise.", 50, "Lane discipline"],
  ["A yellow-box junction should be entered only when:", ["Traffic is moving slowly", "You can clear it without stopping", "You are turning right", "The light is green"], 1, "Do not stop in a yellow box; enter only when your exit is clear.", 54, "Junctions"],
  ["What following gap should you normally use in good conditions?", ["One second", "Two seconds", "Three seconds", "Five seconds"], 2, "Use the three-second rule and increase the gap in poor conditions.", 61, "Safe following distance"],
  ["Before moving off, which is the safest sequence?", ["Signal, move, mirror", "Mirror, signal, move when safe", "Move, signal, mirror", "Horn, signal, move"], 1, "Check mirrors, signal where needed, and move only when safe.", 60, "Moving off"],
  ["What should you do if an emergency vehicle approaches using sirens or flashing lights?", ["Speed up", "Stop immediately in any lane", "Give way safely and do not obstruct it", "Follow it closely"], 2, "Make safe room for the emergency vehicle; do not create a new hazard.", 62, "Emergency vehicles"],
  ["Using a mobile communication device while driving is:", ["Allowed at traffic lights", "Allowed if held below the window", "Not allowed unless hands-free and used safely", "Allowed on expressways"], 2, "Do not hold or use a mobile device while driving; use must not distract you.", 59, "Mobile devices"],
  ["At a red traffic light, you must:", ["Slow down and proceed if clear", "Stop before the stop line", "Stop after the junction", "Honk before moving"], 1, "Stop at the stop line; if none, stop before the junction.", 44, "Traffic lights"],
  ["An amber light means:", ["Accelerate through", "Stop unless you are so close that stopping safely is not possible", "Proceed as normal", "Turn only"], 1, "Amber warns that red is imminent; stop if it is safe to do so.", 44, "Traffic lights"],
  ["When overtaking, you should return to the left lane:", ["As soon as your front bumper passes", "Only after you can safely clear the vehicle", "Immediately after signalling", "Never on an expressway"], 1, "Return only when you have safely passed and can see sufficient clearance.", 50, "Overtaking"],
  ["Road-hogging means:", ["Driving too near the kerb", "Remaining in a right lane without a valid reason", "Driving below 50 km/h", "Stopping at a junction"], 1, "Keep left when not overtaking to avoid obstructing faster traffic.", 52, "Lane discipline"],
  ["When reversing, you should:", ["Rely only on reverse sensors", "Reverse quickly to minimise risk", "Check all around and reverse slowly when safe", "Use hazard lights only"], 2, "Look around, check blind areas, and reverse slowly with full control.", 62, "Reversing"],
  ["A seat belt should be worn by:", ["The driver only", "Front-seat passengers only", "All occupants where belts are fitted", "Children only"], 2, "Wear seat belts wherever they are fitted and available.", 57, "Seat belts"],
  ["Alcohol affects driving mainly by:", ["Improving confidence", "Reducing reaction time and judgement", "Improving night vision", "Making following safer"], 1, "Alcohol impairs judgement, coordination and reaction time.", 58, "Alcohol"],
  ["At a pedestrian crossing, you should:", ["Maintain speed if no one is in front", "Slow down and be ready to stop", "Overtake a stopped vehicle", "Sound the horn continuously"], 1, "Approach cautiously and give way to pedestrians/cyclists crossing or about to cross.", 62, "Pedestrian safety"],
  ["Before entering an expressway, you should:", ["Stop at the end of the slip road", "Use the acceleration lane to match traffic safely", "Enter at the slowest possible speed", "Drive on the road shoulder"], 1, "Use the acceleration lane and merge only when it is safe.", 54, "Expressways"],
  ["In a tunnel, if your vehicle breaks down, the first priority is to:", ["Reverse out", "Protect yourself and other road users, then seek help", "Leave the vehicle in a live lane", "Turn off all lights"], 1, "Follow tunnel emergency procedures and move to safety if possible.", 83, "Tunnel driving"],
  ["A school zone requires drivers to:", ["Assume children will always use crossings", "Reduce speed and watch carefully for children", "Use the horn at every junction", "Overtake buses quickly"], 1, "Drive slowly and expect children to behave unpredictably.", 76, "Special zones"],
  ["If another vehicle is tailgating you, you should:", ["Brake sharply", "Increase your following distance and let it pass safely", "Speed up beyond the limit", "Block the lane"], 1, "Create more space ahead and let the tailgater pass when safe.", 60, "Tailgating"],
  ["When may you use the horn?", ["To show frustration", "To greet a friend", "To warn others of danger", "At every green light"], 2, "Use the horn only as a warning, not as an expression of impatience.", 57, "Lights and signals"],
  ["At night, you should dip your headlights:", ["When meeting or following another vehicle", "Only when stationary", "Only in a car park", "Never on an expressway"], 0, "Dipped headlights avoid dazzling other road users.", 57, "Lights"],
  ["The safest driving technique is best described as:", ["Assuming others will follow rules", "Defensive driving that anticipates hazards", "Driving close to reduce gaps", "Using the horn often"], 1, "Defensive driving means observing, anticipating, and leaving safety margins.", 65, "Defensive driving"],
  ["A vehicle must not be parked where it:", ["Is close to your destination", "Obstructs traffic or creates danger", "Has its engine off", "Is in a quiet street"], 1, "Stopping and parking must not obstruct, endanger or inconvenience others.", 56, "Stopping and parking"],
  ["If you miss your expressway exit, you should:", ["Reverse carefully", "Make a U-turn", "Continue to the next exit", "Stop on the shoulder"], 2, "Never reverse, turn around or stop unnecessarily on an expressway.", 54, "Expressways"],
  ["A solid white line generally means:", ["You may cross whenever convenient", "A restriction applies and it should not be crossed casually", "Parking is permitted", "The road is one-way"], 1, "Treat solid lines as a restriction; obey the associated road situation and markings.", 35, "Road markings"],
  ["When turning at a junction, you must give way to:", ["Pedestrians crossing the road you are turning into", "Only cars travelling behind you", "Vehicles waiting at red", "Nobody when your arrow is green"], 0, "Turning drivers must check and give way to pedestrians/cyclists where required.", 62, "Junction safety"],
  ["What is the main purpose of traffic signs?", ["Decorate roads", "Regulate traffic and warn/inform road users", "Replace all road markings", "Only direct tourists"], 1, "Signs regulate traffic and warn or inform road users.", 9, "Signs and signals"]
];

export const textQuestions: BttQuestion[] = textSeed.map(([prompt, options, answer, explanation, page, topic], index) => ({ id: `t${index + 1}`, kind: "text", prompt, options, answer, explanation, page, topic }));

const visualSeed: Array<[string, string[], number, string, number, string, string]> = [
  ["Identify this mandatory sign.", ["Turn left only", "Turn right only", "Keep left", "Ahead only"], 1, "This mandatory sign requires traffic to turn right.", 9, "Mandatory signs", "sign_01.png"],
  ["Identify this mandatory sign.", ["Turn right only", "Keep left", "Turn left only", "Ahead only"], 2, "This mandatory sign requires traffic to turn left.", 9, "Mandatory signs", "sign_02.png"],
  ["Identify this mandatory sign.", ["Turn left only", "Turn right only", "Ahead only", "Keep left"], 2, "This mandatory sign requires traffic to proceed ahead.", 9, "Mandatory signs", "sign_03.png"],
  ["Identify this mandatory sign.", ["Turn right ahead", "Turn left ahead", "Turn right only", "U-turn permitted"], 0, "Traffic may turn right or continue ahead.", 9, "Mandatory signs", "sign_04.png"],
  ["Identify this mandatory sign.", ["Turn left ahead", "Turn right ahead", "Keep left", "Ahead only"], 0, "Traffic may turn left or continue ahead.", 9, "Mandatory signs", "sign_05.png"],
  ["Identify this mandatory sign.", ["Keep right", "Keep left", "Split traffic", "Turn left only"], 1, "Vehicles must keep to the left of the obstruction.", 9, "Mandatory signs", "sign_06.png"],
  ["Identify this mandatory sign.", ["Split traffic", "Keep left", "Keep right", "Ahead only"], 0, "Vehicles may pass on either side of the obstruction.", 9, "Mandatory signs", "sign_07.png"],
  ["Identify this sign.", ["Give way", "Stop", "No entry", "Stop for children"], 1, "You must stop before the white line and give way as required.", 10, "Mandatory signs", "sign_08.png"],
  ["Identify this sign.", ["Stop", "Give way", "Stop for children", "No stopping"], 2, "This sign requires vehicles to stop for children crossing.", 10, "Mandatory signs", "sign_09.png"],
  ["Identify this sign.", ["Stop", "Give way", "No entry", "Road closed"], 1, "Slow down, stop if needed and give way to traffic on the major road.", 10, "Mandatory signs", "sign_10.png"],
  ["What does this prohibitory sign mean?", ["No entry for all vehicles", "No stopping", "No waiting", "No parking"], 0, "No vehicle may enter from this direction.", 11, "Prohibitory signs", "sign_11.png"],
  ["What does this prohibitory sign mean?", ["No waiting", "No stopping", "No loading or unloading", "No entry"], 1, "Stopping is prohibited.", 11, "Prohibitory signs", "sign_12.png"],
  ["What does this prohibitory sign mean?", ["No right turn", "No left turn", "No U-turn", "Turn right only"], 0, "A right turn is prohibited.", 11, "Prohibitory signs", "sign_13.png"],
  ["What does this prohibitory sign mean?", ["No waiting", "No stopping", "No parking", "No loading or unloading"], 0, "Waiting is prohibited, except as permitted by the rule.", 11, "Prohibitory signs", "sign_14.png"],
  ["What does this sign show?", ["Width limit", "Height limit", "Weight limit", "Speed limit"], 0, "Vehicles wider than the stated width are prohibited.", 12, "Regulatory signs", "sign_17.png"],
  ["What does this sign show?", ["Width limit", "Height limit", "Weight limit", "Vehicle length limit"], 1, "Vehicles higher than the stated height are prohibited.", 12, "Regulatory signs", "sign_18.png"],
  ["What does this road marking require?", ["Give way to traffic on the major road", "Stop at a red light only", "No parking", "Make a U-turn"], 0, "Parallel broken white lines show that traffic approaching must give way to traffic on a major road.", 35, "Road markings", "road-give-way.png"],
  ["What should you do at this marking?", ["Stop close to and before the line", "Park on the line", "Accelerate through", "Overtake on the right"], 0, "A horizontal single white line requires traffic to stop close to and before it.", 35, "Road markings", "road-stop-line.png"],
  ["What does the green directional arrow permit?", ["Turn only after a full stop", "Go in the direction shown", "Proceed in any direction", "Make a U-turn"], 1, "A green arrow permits traffic to proceed in the indicated direction.", 45, "Traffic lights", "traffic-green-arrow.png"],
  ["Which vehicles must stop for this police signal?", ["Vehicles approaching the officer from the front and behind", "Vehicles approaching only from the left", "Vehicles approaching only from the right", "No vehicles"], 0, "The handbook signal directs vehicles approaching from the front and behind to stop.", 48, "Police signals", "police-signal.png"]
];

export const visualQuestions: BttQuestion[] = visualSeed.map(([prompt, options, answer, explanation, page, topic, image], index) => ({ id: `v${index + 1}`, kind: "visual", prompt, options, answer, explanation, page, topic, image: `/btt-visuals/${image}` }));
export const allQuestions = [...textQuestions, ...visualQuestions];
